### PR TITLE
Export `fetch` as default in TypeScript

### PR DESCRIPTION
**Pull request by scottrippey**
This solves https://github.com/arantes555/electron-fetch/issues/6

### CODE REVIEW

**Comment by arantes555** [comment]
@scottrippey Thanks for the PR ! I'm not a typescript user myself, so I'm glad other people can take care of this...

Do you think you could add a very simple typescript compilation test to your PR, and add it to the `package.json` "test" script, so such problems don't happen again in the future ?

If it's a bother for you, I'll accept the PR as is.

**Comment by scottrippey** [comment]
Makes sense, I do love test coverage, even for "documentation" like this!

To test this, I'll probably need to bring in TypeScript as a `devDependency`, and might also create a `test.ts` file.  Any objections to that?

**Comment by arantes555** [comment]
@scottrippey nope, nous objections, that's pretty much what I had in mind :)

**Comment by markmcdowell** [comment]
Any chance we could merge this as is? It's a bit of pain to have to redefine the typing.

**Comment by Anrock** [comment]
Any progress on this?

**Comment by scottrippey** [comment]
Sorry, I never had time to add test coverage!  Thanks for merging as-is ... I'm sure it'll help folks out!

**Comment by arantes555** [comment]
@scottrippey I didn't, I added the tests myself 😜

**Pull request merged**
